# Generated by Django 4.1 on 2022-11-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_rename_payment_details_payment_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_detail',
            name='payment_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
