# Generated by Django 4.1 on 2022-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_remove_payment_detail_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_detail',
            name='payment_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
